from setuptools import setup, find_packages
from os import path

here = path.abspath(path.dirname(__file__))

setup(
    name='pyresparser',
    version='1.0.6',
    description='A simple resume parser used for extracting information from resumes',
    long_description=open('README.rst').read(),
    url='git@github.com:yugalkaushik/resumeparser.git',
    author='Yugal Kaushik',
    author_email='yugalkauhshik14@gmail.com',
    license='GPL-3.0',
    include_package_data=True,
    classifiers=[
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    packages=find_packages(),
    install_requires=[
        'attrs>=21.1.0',
        'blis>=0.7.0',
        'certifi>=2021.10.8',
        'chardet>=4.0.0',
        'cymem>=2.0.5',
        'docx2txt>=0.8',
        'idna>=3.0',
        'jsonschema>=4.0.0',
        'murmurhash>=1.0.5',
        'nltk>=3.6.0',
        'numpy>=1.21.0',
        'pandas>=1.3.0',
        'pdfminer.six>=20211012',
        'plac>=1.3.0',
        'preshed>=3.0.0',
        'pycryptodome>=3.12.0',
        'pyrsistent>=0.18.0',
        'python-dateutil>=2.8.0',
        'pytz>=2021.3',
        'requests>=2.27.0',
        'six>=1.16.0',
        'sortedcontainers>=2.4.0',
        'spacy>=3.0.0',
        'srsly>=2.4.0',
        'thinc>=8.0.0',
        'tqdm>=4.62.0',
        'urllib3>=1.26.0',
        'wasabi>=0.8.0',
        'setuptools>=60.0.0',
    ],
    zip_safe=False,
    entry_points = {
        'console_scripts': ['pyresparser=pyresparser.command_line:main'],
    }
)